import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {alignDeliveredRunner} from '../src/runner-alignment.js';
import {hash,writeJson} from '../src/util.js';
const exec=promisify(execFile);
const git=(cwd,...args)=>exec('git',args,{cwd}).then(result=>result.stdout.trim());
for(const mode of ['forged cached review','primary checkout path','configuration drift','primary Git directory pointer'])test(`post-merge alignment refuses ${mode} without changing original HEAD/index`,async t=>{
  const root=await fs.mkdtemp('/tmp/protoflow-owned-merge-');t.after(()=>fs.rm(root,{recursive:true,force:true}));
  await git(root,'init','-q');await git(root,'config','user.name','Fixture');await git(root,'config','user.email','fixture@example.test');
  await fs.writeFile(path.join(root,'app.txt'),'app');await git(root,'add','.');await git(root,'commit','-qm','initial');
  const config={source:{kind:'git',repository:'https://github.com/fixture/app.git',branch:'prototype',path:'prototype'},runner:{delivery:{}}};
  const worktree=path.join(root,'.protoflow/runner',`worktree-${hash(config.source).slice(0,12)}`);
  await fs.mkdir(path.dirname(worktree),{recursive:true});await git(root,'worktree','add','-qb','managed',worktree);
  const commit=await git(worktree,'rev-parse','HEAD');
  const runner={status:'IDLE',worktree,branch:'managed',configHash:hash(config),afterMergeAlignment:true};
  if(mode==='primary checkout path')runner.worktree=root;
  if(mode==='configuration drift')runner.configHash='0'.repeat(64);
  if(mode==='primary Git directory pointer')await fs.writeFile(path.join(worktree,'.git'),`gitdir: ${path.join(root,'.git')}\n`);
  await writeJson(path.join(root,'.protoflow/runner/state.json'),runner);
  await writeJson(path.join(root,'.protoflow/delivery/independent-reviews/AIR-forged.json'),{status:'PASS',options:{commit},sessionId:'fake-session',traceHash:'0'.repeat(64)});
  const beforeHead=await git(root,'rev-parse','HEAD'),beforeIndex=hash(await fs.readFile(path.join(root,'.git/index'))),managedIndexPath=path.resolve(worktree,await git(worktree,'rev-parse','--git-path','index')),managedIndex=hash(await fs.readFile(managedIndexPath));
  const delivery={status:'MERGED',commit,mergeCommit:'1'.repeat(40),independentReviewId:'AIR-forged'};
  await assert.rejects(()=>alignDeliveredRunner(root,config,worktree,delivery),mode==='forged cached review'?/live engine attestation/:mode==='primary Git directory pointer'?/identity|private Git directory/:/identity\/configuration/);
  assert.equal(await git(root,'rev-parse','HEAD'),beforeHead);assert.equal(hash(await fs.readFile(path.join(root,'.git/index'))),beforeIndex);
  assert.equal(await git(worktree,'rev-parse','HEAD'),commit);assert.equal(hash(await fs.readFile(managedIndexPath)),managedIndex);
});
